### PR TITLE
Fix exclude cdn option

### LINKED ISSUE #1417: -ec flag is ignored when -ports is used
### httpx version:
v1.3.5

### Current Behavior:
httpx ignores the `-ec` flag when passing the `-ports` argument

### Expected Behavior:
CDN hosts are excluded

### Steps To Reproduce:
```bash
echo HOST | httpx -ec -threads 300 -no-fallback -random-agent -ports 80,443
```

image

### PR DESCRIPTION
**Pull request by RamanaReddy0M**
- closes #1417 

```console
✗ go run . -u projectdiscovery.io,scanme.sh -cdn -e cdn

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

                projectdiscovery.io

[INF] Current httpx version v1.3.9 (latest)
https://scanme.sh
```

### CODE REVIEW

File: runner/runner.go [hunk 1]
```diff
@@ -2267,6 +2267,9 @@ func (r *Runner) skipCDNPort(host string, port string) bool {
 		return false
 	}
 
+	if sliceutil.Contains(r.options.Exclude, "cdn") && isCdnIP {
```
Comment (dogancanbakir) [inline runner/runner.go:2270]: we can use `r.scanopts.ExcludeCDN` instead of `sliceutil.Contains(r.options.Exclude, "cdn")`. But I think there is no need for that since we're checking at the beginning of this func.

Comment (RamanaReddy0M) [reply runner/runner.go]: > Also, we're changing the behavior of this function by only checking against `isCdnIP`. Intented?

Previously observed that the logic isn't working without custom ports. But this seems conflicting, Updated the logic to check on custom ports with existing behaviour. can you test now?
cc: @dogancanbakir

**Review by Mzack9999 — APPROVED** [review]
lgtm - As a follow up I think we can also create an issue in [utils](https://github.com/projectdiscovery/utils) to use standard library calls (eg. `slices.Contains(..)` from go 1.21 or just use them directly. They had meaning when they were missing from the language standard library.

**Review by dogancanbakir — APPROVED** [review]
