### PR TITLE
Fixed reading input file with -l

### LINKED ISSUE #123: Issue with file read input flag
Reproduce with:

```sh
$ echo -e "example.com\ngoogle.com" > x
$ httpx -l x
```

Expected:

```
http://example.com
https://exampe.com
http://google.com
https://google.com
```

Outcome: none

Obtain expected outcome with:

```sh
$ httpx < x
```

### PR DESCRIPTION
**Pull request by vzamanillo**
Fixes #123 but is not related to #122.

This bug was introduced on #117, closing the input file has to be deferred or we will try to read from a closed stream.

### CODE REVIEW

File: common/fileutil/fileutil.go [hunk 1]
```diff
@@ -24,8 +24,10 @@ func HasStdin() bool {
 		return false
 	}
 
-	isPipedFromChrDev := (stat.Mode() & os.ModeCharDevice) == 0
-	isPipedFromFIFO := (stat.Mode() & os.ModeNamedPipe) != 0
+	mode := stat.Mode()
+
+	isPipedFromChrDev := (mode & os.ModeCharDevice) == 0
+	isPipedFromFIFO := (mode & os.ModeNamedPipe) != 0
```
Comment (vzamanillo) [inline common/fileutil/fileutil.go:30]: This changes can be replicated to other projects (subfinder, naabu and nuclei) to fix an small delay while checking stdin.
