### PR TITLE
Fixing https with burp

### LINKED ISSUE #724: https randomly failing with proxies
### httpx version:
`master/main` and `dev`

### Current Behavior:
`https` urls are failing silently in certain cases while using proxy

### Expected Behavior:
`https` protocol working correctly with proxies

### Steps To Reproduce:
```console
$ echo https://192.168.1.1 | go run . -proxy http://localhost:8080 -v
...
[DBG] Failed 'https://192.168.1.1': remote error: tls: user canceled
```
Screenshot 2022-08-09 at 11 25 47

### PR DESCRIPTION
**Pull request by Mzack9999**
## Description
This PR attempts to fix #724 by ~~lowering TLS max version to 1.2 when burp proxy is used~~ ignoring tls contextual errors

### CODE REVIEW

File: common/httpx/httpx.go [hunk 1]
```diff
@@ -113,6 +113,12 @@ func New(options *Options) (*HTTPX, error) {
 		},
 		DisableKeepAlives: true,
 	}
+	// go clients have issues with java based proxies in case of Tls 1.3 and when the 'Connection: close'
+	// header is present, since the latter is added automatically by the go standard library we opt to lower
+	// max tls version to 1.2 when a proxy is used and most likely matches burp suite
+	if stringsutil.HasSuffixAny(httpx.Options.HTTPProxy, "127.0.0.1:8080", "localhost:8080") {
+		transport.TLSClientConfig.MaxVersion = tls.VersionTLS12
```
Comment (Ice3man543) [inline common/httpx/httpx.go:120]: shouldn't it be better to enable this compatability related behaviour with a flag?

**Review by Ice3man543 — APPROVED** [review]
approved with a comment

File: common/httpx/httpx.go (hunk 1 above)
Comment (Mzack9999) [reply common/httpx/httpx.go:120]: I'm just not sure how intuitive it would be to use it. What do you think about performing an automatic connectivity test with the proxy? Then, in case of a `tls: user canceled` error, switching to TLS 1.2?

Comment (Ice3man543) [reply common/httpx/httpx.go:120]: yeah that sounds better

Comment (Mzack9999) [reply common/httpx/httpx.go]: found a better solution just by ignoring tls contextual errors

**Review by Ice3man543 — APPROVED** [review]

**Review by ehsandeep — CHANGES_REQUESTED** [review]
In this case, while using burp, the server returns true, even though there is no dns record associated with it.

```
echo o2.email.hackerone.com | ./httpx -proxy http://127.0.0.1:8080/

https://o2.email.hackerone.com
```

**Comment by Mzack9999** [comment]
@ehsandeep Looks like it's burp responding with an HTML page telling the domain is invalid:
```console
$ curl https://o2.email.hackerone.com -x http://127.0.0.1:8080 -k
<html><head><title>Burp Suite Community Edition</title>
<style type="text/css">
body { background: #dedede; font-family: Arial, sans-serif; color: #404042; -webkit-font-smoothing: antialiased; }
#container { padding: 0 15px; margin: 10px auto; background-color: #ffffff; }
a { word-wrap: break-word; }
a:link, a:visited { color: #e06228; text-decoration: none; }
a:hover, a:active { color: #404042; text-decoration: underline; }
h1 { font-size: 1.6em; line-height: 1.2em; font-weight: normal; color: #404042; }
h2 { font-size: 1.3em; line-height: 1.2em; padding: 0; margin: 0.8em 0 0.3em 0; font-weight: normal; color: #404042;}
.title, .navbar { color: #ffffff; background: #e06228; padding: 10px 15px; margin: 0 -15px 10px -15px; overflow: hidden; }
.title h1 { color: #ffffff; padding: 0; margin: 0; font-size: 1.8em; }
div.navbar {position: absolute; top: 18px; right: 25px;}
div.navbar ul {list-style-type: none; margin: 0; padding: 0;}
div.navbar li {display: inline; margin-left: 20px;}
div.navbar a {color: white; padding: 10px}
div.navbar a:hover, div.navbar a:active {text-decoration: none; background: #404042;}
</style>
</head>
<body>
<div id="container">
<div class="title"><h1>Burp Suite Community Edition</h1></div>
<h1>Error</h1><p>Unknown&#32;host&#58;&#32;o2&#46;email&#46;hackerone&#46;com</p>
<p>&nbsp;</p>
</div>
</body>
</html>
```
